### PR TITLE
[WIP] Fix dependency generation issues

### PR DESCRIPTION
**Pull request by Conan-Kudo**
This pull request is aimed to resolve issues described in #25. Namely, it reverts a previous commit which broke things further and alters the regular expression for filtering package names to accept packages that have a "+" character in the name.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@ascherer By all rights, this should work, but it's not. What am I doing wrong here that still causes `libstdc++6` to be recorded as `6`?

**Comment by ascherer** [comment]
`+` is the 'one or more' regex quantifier, so it should be escaped as `\+`.

**Comment by Conan-Kudo** [comment]
@ascherer I shouldn't need to, because `\w` already matches the list literally. In fact, I think escaping it pulls it out of the list...

**Comment by ascherer** [comment]
You are right that `+` in the 'character class'  doesn't have to be escaped. On the other hand,
`[\w.\+-]+?` works just as well as `\S+?`.

**Comment by Conan-Kudo** [comment]
@ascherer That doesn't work either. Is there a way we can make it show us what's going on?

**Comment by ascherer** [comment]
It's a matter with Ubuntu 14.04 (Linux Mint 17.2). When I run **debbuild** on one of my test specs, `getreqs()` not only finds `libc6`, but also `i386` (similar to your `amd64`).
```
dpkg-query -S /lib/i386-linux-gnu/libc.so.6
```
produces
```
libc6:i386: /lib/i386-linux-gnu/libc.so.6
```
Debugging is possible by adding `use re 'debug';` in [line 1640](https://github.com/ascherer/debbuild/blob/master/debbuild#L1640).

**Comment by ascherer** [comment]
Commit 94b42b0 fixes issue #25.

**Pull request closed without merging**
